import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Bg from '@/components/Bg'
import Button from '@/components/Button'
import { Dialog, DialogClose, DialogContent } from '@/components/Dialog'
import Footer from '@/components/Footer'

import './globals.css'

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru" className={inter.variable}>
      <body>
        <div className="bg-black-soft relative isolate mx-auto h-(--tg-viewport-stable-height,100dvh) max-w-[430px] overflow-clip">
          <Bg />
          {children}
          <Footer />
        </div>

        <svg xmlns="http://www.w3.org/2000/svg" className="hidden">
          <filter
            id="liquid-glass"
            x="0%"
            y="0%"
            width="100%"
            height="100%"
            filterUnits="objectBoundingBox"
          >
            <feComponentTransfer in="SourceAlpha" result="alpha">
              <feFuncA type="identity"></feFuncA>
            </feComponentTransfer>

            <feGaussianBlur
              in="alpha"
              stdDeviation="20"
              result="blur"
            ></feGaussianBlur>

            <feDisplacementMap
              in="SourceGraphic"
              in2="blur"
              scale="12"
              xChannelSelector="A"
              yChannelSelector="A"
            ></feDisplacementMap>
          </filter>
        </svg>

        <Dialog>
          <DialogContent>
            <h3 className="mb-6 text-center text-3xl font-bold">Ошибка</h3>
            <p className="mb-6 text-center text-xl font-medium text-white/65">
              Текст ошибки
            </p>
            <DialogClose
              render={
                <Button className="min-h-10 w-full text-xl font-medium">
                  Закрыть
                </Button>
              }
            />
          </DialogContent>
        </Dialog>
      </body>
    </html>
  )
}
