import type { Metadata } from 'next'

import Bg from '@/components/Bg'
import Button from '@/components/Button'
import { Dialog, DialogClose, DialogContent } from '@/components/Dialog'
import Footer from '@/components/Footer'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <head>
        <link
          rel="preload"
          href="/fonts/Inter-Regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <div className="app">
          <Bg />
          {children}
          <Footer />
        </div>

        <svg xmlns="http://www.w3.org/2000/svg" className="hidden">
          <filter
            id="liquid-glass"
            x="0%"
            y="0%"
            width="100%"
            height="100%"
            filterUnits="objectBoundingBox"
          >
            <feComponentTransfer in="SourceAlpha" result="alpha">
              <feFuncA type="identity"></feFuncA>
            </feComponentTransfer>

            <feGaussianBlur
              in="alpha"
              stdDeviation="20"
              result="blur"
            ></feGaussianBlur>

            <feDisplacementMap
              in="SourceGraphic"
              in2="blur"
              scale="12"
              xChannelSelector="A"
              yChannelSelector="A"
            ></feDisplacementMap>
          </filter>
        </svg>

        <Dialog>
          <DialogContent>
            <h3 className="mb-6 text-center text-3xl font-bold">Ошибка</h3>
            <p className="mb-6 text-center text-xl font-medium text-white/65">
              Текст ошибки
            </p>
            <DialogClose
              render={
                <Button className="min-h-10 w-full text-xl font-medium">
                  Закрыть
                </Button>
              }
            />
          </DialogContent>
        </Dialog>
      </body>
    </html>
  )
}
